name: Run Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # os: [ubuntu-latest, macos-latest, windows-latest]
                os: [ubuntu-latest]
                python-version: [3.6, 3.7, 3.8]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install -r requirements.txt
            - name: Fix line
              run: sed -i 's/from \.output import Output/from .output import Output, Input, Inputs/' $(python -c "import os; import pulumi.resource as resource; print(os.path.abspath(resource.__file__))")
            - name: Run tests
              run: |
                python -m unittest discover -s lib/test -v
